#!/usr/bin/env bash
set -e

source crc.env

crc stop

sudo qemu-img resize ~/.crc/machines/crc/crc +20G

crc start

eval $(crc oc-env)
oc login -u kubeadmin -p $(crc console --credentials | awk -F "kubeadmin" '{print $2}' | cut -c 5- | rev | cut -c31- | rev) https://api.crc.testing:6443

ssh -i ~/.crc/machines/crc/id_rsa -o StrictHostKeyChecking=no core@$(crc ip) << EOF
  sudo xfs_growfs /sysroot/
EOF

oc patch --type=merge --patch='{
  "metadata": {
    "labels": {
      "master": "true"
    }
  }
}' node/$(oc get nodes | grep -v NAME | awk '{print $1}')

cat <<EOF | oc apply -f -
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  annotations:
     storageclass.kubernetes.io/is-default-class: "true"
  name: standard
provisioner: kubernetes.io/no-provisioner
EOF

oc patch --type=merge --patch='{
  "spec": {
    "storageClassName": "standard" 
  }
}' pv/pv0002

oc patch --type=merge --patch='{
  "spec": {
    "storageClassName": "standard" 
  }
}' pv/pv0003

oc patch --type=merge --patch='{
  "spec": {
    "storageClassName": "standard" 
  }
}' pv/pv0004

oc patch --type=merge --patch='{
  "spec": {
    "storageClassName": "standard" 
  }
}' pv/pv0005
