#!/usr/bin/env bash
set -e

source crc.env

echo "======================================================"
echo "Deleting crc ${CRC_VERSION}"
echo "======================================================"
crc delete --force

rm ~/crc

sudo virsh undefine crc
sudo virsh destroy  crc
