#!/usr/bin/env bash
set -e

source crc.env

echo "======================================================"
echo "Cleaning crc ${CRC_VERSION}"
echo "======================================================"
crc cleanup --force
